services:
  consultar:
    build: ./consult-service
    volumes:
      - ./consult-service:/app
    ports:
      - "3005:3005"
    networks:
      - internal-network

  crear:
    build: ./crud-service
    volumes:
      - ./crud-service:/app
    ports:
      - "3010:3010"
    networks:
      - internal-network

  logs:
    build: ./logs-service
    volumes:
      - ./logs-service:/app
    ports:
      - "3015:3015"
    networks:
      - internal-network

  toponomia:
    build: ./toponimia-service
    volumes:
      - ./toponimia-service:/app
    ports:
      - "3020:3020"
    networks:
      - internal-network

  mongo:
    image: mongo:latest
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network
      
networks:
  internal-network:
  
volumes:
  mongo-data: